### PR TITLE
Passing createSNSEvent options

### PR DESCRIPTION
**Pull request by Jbarget**
- adds functionality to pass options to createSNSEvent (only option at the moment is for a custom `message`)
- adds tests for functionality
- updates readme for functionality

### CODE REVIEW

**Comment by Jbarget** [comment]
I wasn't too sure what options to actually pass through to the helper. At the moment its just message but are there others you think i should add?

**Review by nelsonic — APPROVED** [review]
@Jbarget this looks good. 👍 
As for adding other options we tend to add on a "needs basis". 😉

**Comment by Jbarget** [comment]
👍

**Comment by nelsonic** [comment]
@Jbarget `aws-lambda-test-utils@1.2.0` on NPM FYI! 🎉

**Pull request merged**
