### PR TITLE
adding getRemainingTimeInMillis to mockContext object

### PR DESCRIPTION
**Pull request by benjaminlees**
this should solve issue #5 please review @nikhilaravi.

### CODE REVIEW

**Comment by nikhilaravi** [comment]
@benjaminlees nice! Looks great! I just edited one line in the test to get 100% coverage! :umbrella: 
Thanks so much! :) Will merge it now!

**Comment by nelsonic** [comment]
@nikhilaravi would you mind bumping up the package version number in `package.json` before merging so you can `npm publish` the new version? :100:

**Comment by nikhilaravi** [comment]
@nelsonic yes sure! :)

**Comment by nelsonic** [comment]
Amaze! :rocket:

**Pull request merged**
